<a href="https://colab.research.google.com/github/ilrnd/GoogleColab-HT-/blob/main/HT10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задача 44: В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

In [1]:
import pandas as pd

In [5]:
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  human
1  human
2  robot
3  human
4  human

In [29]:
data.loc[data['whoAmI']=='human','human'] = 1
data.loc[data['whoAmI']=='robot','human'] = 0
data.loc[data['whoAmI']=='robot','robot'] = 1
data.loc[data['whoAmI']=='human','robot'] = 0

In [28]:
data

   whoAmI human  robot
0   human     1    0.0
1   human     1    0.0
2   robot     0    1.0
3   human     1    0.0
4   human     1    0.0
5   robot     0    1.0
6   human     1    0.0
7   robot     0    1.0
8   robot     0    1.0
9   robot     0    1.0
10  robot     0    1.0
11  human     1    0.0
12  human     1    0.0
13  robot     0    1.0
14  robot     0    1.0
15  human     1    0.0
16  robot     0    1.0
17  human     1    0.0
18  human     1    0.0
19  robot     0    1.0

Решение через **get_dummies**

In [31]:
pd.get_dummies(data['whoAmI'])

    human  robot
0       1      0
1       1      0
2       0      1
3       1      0
4       1      0
5       0      1
6       1      0
7       0      1
8       0      1
9       0      1
10      0      1
11      1      0
12      1      0
13      0      1
14      0      1
15      1      0
16      0      1
17      1      0
18      1      0
19      0      1